- name: Deploy Web SSL Full Strict
  hosts: all
  become: yes
  tasks:
    - name: 1. Đảm bảo Nginx hiện diện
      apt:
        name: nginx
        state: present

    - name: 3. Chép chứng chỉ SSL vào ĐÚNG chỗ
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "server.crt", dest: "/server.crt" }
        - { src: "server.key", dest: "/server.key" }

    - name: 4. Chép code Web
      copy:
        src: index.html
        dest: /var/www/app/index.html

    - name: 5. Cấu hình Nginx cổng 443
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              listen [::]:80;
              server_name _;
              return 301 https://$host$request_uri;
          }
          server {
              listen 443 ssl;
              listen [::]:443 ssl;
              server_name _;

              ssl_certificate /etc/nginx/ssl/server.crt;
              ssl_certificate_key /etc/nginx/ssl/server.key;

              root /var/www/app;
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: 6. Restart Nginx
      service:
        name: nginx
        state: restarted
