version: '3'

services:
  web:
    image: nginx:latest
    container_name: static-web
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - /opt/app/html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf