name: Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: set deploy path
        id: path
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "TARGET=/var/www/dev" >> $GITHUB_OUTPUT

          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "TARGET=/var/www/staging" >> $GITHUB_OUTPUT

          else
            echo "TARGET=/var/www/prod" >> $GITHUB_OUTPUT
          fi

      - name: deploy
        run: |
          rsync -avz --delete ./ \
            root@${{ secrets.HOST }}:${{ steps.path.outputs.TARGET }}
