name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Vào thư mục
            sudo mkdir -p /var/www/app
            cd /var/www/app

            # 2. Xử lý triệt để vụ thư mục không trống
            if [ -d ".git" ]; then
              echo "Đang cập nhật code mới..."
              sudo git fetch --all
              sudo git reset --hard origin/main
            else
              echo "Thư mục có file rác nhưng chưa có Git, đang dọn dẹp để clone mới..."
              # Xóa sạch nội dung bên trong để clone không bị lỗi
              sudo rm -rf ..?* .[!.]* * sudo git clone https://github.com/Dung996/deploy-web.git .
            fi

            # 3. Kiểm tra file docker-compose.yml trước khi chạy
            if [ -f "docker-compose.yml" ]; then
              sudo docker compose up -d --build
            else
              echo "LỖI: Không tìm thấy file docker-compose.yml trong repo!"
              exit 1
            fi
